version: '3.9'

services:
  kotlinapp:
    container_name: kotlinapp
    build: # this is the build context: .
      context: .
      dockerfile: Dockerfile
      args: # these are the arguments that are passed to the dockerfile
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports: # port exposed to the host machine
      - "8080:8080"
    environment: # these are the environment variables that are passed to the dockerfile
      DB_URL: jdbc:postgresql://localhost:5432/itmo-cloud-dev
      PG_USER: postgres
      PG_PASSWORD: admin